Fix 403 when create classroom
FirstianB101/pullgo-server pull request #110
Opened 2021-09-30 07:38 UTC by tellang

close #109 
커밋 내용과 같음,

2021-09-30 16:46 UTC, woodyn1002 requested changes
부모-자식 간 관계를 끊는 방법이 단순히 부모의 컬렉션에서 자식을 제거하는 방식만으로 구현돼있는데
이러면 자식 Entity는 여전히 부모를 참조하고 있으므로, 변경 사항을 한쪽에만 반영하는 셈임
결국 이걸 '연관 관계 편의 메소드'라고 부를 수 없게 되고, 순간적으로 무결성이 깨져보이는 문제가 생길 수 있음

자식 클래스의 `removeThis()`를 제거하고, `setParent(null)` 메소드를 호출하는 방향으로 수정하면 좋을듯

2021-09-30 16:52 UTC, woodyn1002 requested changes
테스트 이름이 테스트 목적을 잘 표현하지 못해서 관리하기가 힘들어질 것 같음
기존 규칙처럼 `When_Given_Then` 형식으로 짓거나, 힘들면 그냥 한글로라도 적는게 좋을 것 같음

2021-10-03 06:24 UTC, yy0867 commented
일 안하냐

2021-10-03 11:04 UTC, woodyn1002 approved these changes

2021-10-03 11:04 UTC, merged