AttenderState, AttenderAnswer 개선
FirstianB101/pullgo-server pull request #118
Opened 2021-10-14 16:04 UTC by tellang

close #71, close #72, close #74 
커밋 내용과 같음

2021-10-14 16:16 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/helper/RepositoryHelper.java
> +        return findOrThrow(AttenderAnswer.class, attenderAnswer.getId());
`findOrThrow` 이 부분 필요한가? 위에서 이미 AttenderAnswer 찾은 것 같은데

2021-10-14 16:19 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/dto/AttenderAnswerDto.java
> +    class Put {
"DTO = Body"인데, Put Body에 `attenderStateId`랑 `questionId`는 필요 없는 것 같음
PathVariable로 주잖음

2021-10-14 16:41 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/dto/AttenderAnswerDto.java
> +    class Put {
그르네

2021-10-15 04:00 UTC, woodyn1002 requested changes
다른거는 다 괜찮은듯

2021-10-15 14:57 UTC, merged