Exam 채점방식 변경
FirstianB101/pullgo-server pull request #149
Opened 2022-01-22 13:07 UTC by tellang

일괄적이었던 `CronJob`을  `Exam`별 최대 종료시점에 비례한 단발적인 예약작업으로 개선

세부사항은 커밋 내용과 같음

2022-01-23 09:39 UTC, woodyn1002 requested changes
근데 주기적으로 확인하는 CronJob은 사라진거임?
그럼 중간에 서버 꺼지면 어떡함?

2022-01-23 09:39 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +        exam = examRepository.save(exam);
cronJob 등록하는 로직을 메소드로 빼는건 어떨까?

첫 번째 장점으로는 메소드 내에서의 추상화 수준을 통일시킬 수 있음
이건 클린 코드에서 나온 용어인데
https://lordofkangs.tistory.com/127
이거 참고해보면 이해할 수 있을거임

두 번째 장점으로 중복 로직을 한 곳에 모을 수 있음
create 뿐만 아니라 update에도 동일한 로직이 있는 것 같은데
코드 중복은 피할 수록 좋을 것 같음

2022-01-23 09:39 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +    public void allExamFinish() {
꼭 수정할 필욘 없지만 finishAllExam이 조금 더 문법에 맞을듯 (메소드 이름은 동사로 작명)

2022-01-23 09:39 UTC, woodyn1002 commented on src/test/java/kr/pullgo/pullgoserver/helper/EntityHelper.java
> +        Long id = exam.getId();
코드 중복2

2022-01-23 09:39 UTC, woodyn1002 commented on src/test/java/kr/pullgo/pullgoserver/ExamIntegrationTest.java
> +            boolean doseOldExamFinish = trxHelper.doInTransaction(() -> {
이것도 문법 얘기라 흘려 들어도 되지만 isOldExamFinished가 맞을 것 같다 (old exam is finished)

2022-01-23 09:39 UTC, woodyn1002 commented on src/test/java/kr/pullgo/pullgoserver/ExamIntegrationTest.java
> +            boolean doseFreshExamOnGoing = trxHelper.doInTransaction(() -> {
마찬가지로 isFreshExamOnGoing일 것 같다 (fresh exam is on going)

2022-01-23 09:39 UTC, woodyn1002 commented on src/test/java/kr/pullgo/pullgoserver/ExamIntegrationTest.java
> +                    Thread.sleep(100);
저번에 테스트 코드에 sleep을 넣는 것에 대해 잠깐 얘기했던 것 같은데, 거기서 조금 더 첨언을 해보자면
조직마다 다르겠지만, '단위 테스트에 집중할 것인가'와 '통합 테스트에 집중할 것인가'에 따라 그 전략이 달라질 것 같다고 최근 느꼈음

단위 테스트에 집중한다는 말은, 단위 테스트를 조밀하게 작성해두고, Spring Context 로드 없이 빠르게 실행할 수 있도록 만드는 것
통합 테스트가 없다면 기능이 제대로 작동하는지 모르는거 아닌가? 하고 생각할 수 있는데,
이 전략의 요점은 개발/테스트/배포가 신속하게 이루어지고, 실제로 일부분 배포해보고 문제가 있다면 빠르게 롤백해서 문제를 해결하는 거임
(물론 단위 테스트를 빡빡하게 작성해두었으니 문제가 자주 터지진 않을 것)

반대로 우리의 방법은 '통합 테스트에 집중하자'인데, 트래픽이 발생하지 않으니 배포를 해도 바로 확인하기 어렵다는 특성에 의한 결정임
단점은 당연히 테스트 실행 속도고, 단위 테스트에 비교적 노력을 쏟지 않으니 추후 리팩토링 시 코드가 망가질 위험에 취약하다는 거

테스트 코드에 sleep을 넣으면서까지 작동을 검증하는 것은 당장의 방향과 맞지만, 이게 항상 옳지는 않다는 것을 생각해두면 좋을 것 같다
가령 프로젝트가 커지면, 100ms씩 기다리는 테스트가 100개만 쌓여도 10초 이상 기다려야 함

2022-01-23 16:00 UTC, tellang commented
> 근데 주기적으로 확인하는 CronJob은 사라진거임? 그럼 중간에 서버 꺼지면 어떡함?

어? 거기까진 생각 못했는디

2022-01-23 16:09 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +        exam = examRepository.save(exam);
사실 'register'메소드 하나긴 해서 좀 애매했음

2022-01-23 16:10 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +    public void allExamFinish() {
이런거 다시보면 이상하더라

2022-03-18 14:51 UTC, woodyn1002 requested changes
늦어서 ㅈㅅ ㅎㅎ;;

2022-03-18 14:51 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/cron/CronJob.java
> +    public Runnable getRunnable(Long id, Runnable runnable, String msg) {
외부로 공개하는 메소드가 아니라면 private으로 두어서 캡슐화 하는게 좋을 것 같다

2022-03-18 14:51 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/exam/ExamManagement.java
> +public class ExamManagement {
CRUD와 분리한 아이디어는 매우 칭찬하지만, 'Management'라는 단어를 클래스 명명에 쓰게되는건 유의해야 할 것 같다
클래스 이름에 '관리'라는 말을 집어넣는 순간, 그 클래스가 아주 많은 책임을 가질 수 있는 짬뽕 클래스로 변할 확률이 높기 때문
당장 지금만 봐도 "Exam의 종료 및 취소 등의 관리 작업"이라고 한다면 벌써 여러 개의 책임이 섞인 모양이다
이는 SRP를 위반하고 시간이 갈 수록 이 클래스의 몸집이 커지게 될 것 같다

지금은 초기라 큰 문제는 없겠지만 가능하다면 ExamCancelService, ExamFinishService와 같이 책임에 따라 클래스를 나누어 주는 것이 좋은 습관일 것 같다

2022-03-18 14:51 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/exam/ExamService.java
> +        manageMent.registerCronJob(exam);
이전 코멘트와 마찬가지로 'ExamManagement는 CronJob 관리의 책임이 있는가'를 다시 한 번 생각해보면 좋을 것 같다

추가로 커밋 메시지에 추상화라고 했는데
오히려 이전 코드가 CronJob 서비스를 가져다 쓰기 때문에 더 추상화된 코드인 것 같다
아마 말하고 싶었던 건 시험에 관한 CronJob 로직을 캡슐화했다는 게 아닐까?

2022-03-18 16:50 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/exam/ExamManagement.java
> +public class ExamManagement {
현재 메소드의 갯수를 생각했을때 Cancel과 Finish를 구별하는것 보다 좀 더 큰 범주인 LifeCycle로 구분하는것이 어떨까

2022-03-18 16:50 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/cron/CronJob.java
> +    public Runnable getRunnable(Long id, Runnable runnable, String msg) {
트랜잭션에 대한 이해가 부족했었나봄

2022-03-18 17:06 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/exam/ExamLifeCycleService.java
> +public class ExamLifeCycleService {
LifeCycle이라는 이름은 조금 부적절한게, create랑 delete는 애초에 CrudService의 몫이라 이 클래스의 책임을 잘 표현해주진 못하는 것 같음
단어 선택을 떠나서 아직 기능이 적다고 해도 "클래스를 책임 단위로 나누기"를 연습해보는 건 좋을 것 같다고 생각함
이름에 대해 고민하고 있다는건 클래스가 가진 책임이 너무 많다는 증거이고, 자바는 원래 클래스를 잘게 나누는 스타일이기도 하고.
굳이 나누기 싫다면 나누지 않았을 때의 장점이 무엇인지 생각해봐도 좋고

https://data-make.tistory.com/641
이건 클린코드에서 나온 내용인데 심심할 때 읽어도 좋을듯

2022-03-18 17:15 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/exam/ExamLifeCycleService.java
> +public class ExamLifeCycleService {
클린코드를 읽었어야 했다

2022-03-19 05:04 UTC, woodyn1002 approved these changes
👍

2022-03-19 05:07 UTC, merged