Exam의 누락되 예외추가
FirstianB101/pullgo-server pull request #63
Opened 2021-03-11 07:09 UTC by tellang

close #58

2021-03-11 07:24 UTC, woodyn1002 requested changes
커밋 메시지 '누락되는'에서 '는'이 누락된듯 ㅋㅋ

2021-03-11 07:24 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +        if (exam.isFinished()) {throw ResponseStatusExceptions.examAlreadyFinished();}
코드 스타일 적용이 안 된 것 같은데 터미널로 커밋한거 아님?
중괄호 블록은 여러 줄로 표현하는게 보기 좋은 것 같음

2021-03-11 07:24 UTC, woodyn1002 commented on src/test/java/kr/pullgo/pullgoserver/ExamIntegrationTest.java
> +        void cancelExam_ExamAlreadyCanceled_BadRequestStatus() throws Exception {
철자 'Canceled' → 'Cancelled'

2021-03-11 07:24 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +            exam.setCancelled(true);
`isCancelled == false`이고 `isFinished == true`일 때 `setCancelled(true)`가 호출되는데 로직에 문제가 있는 것 같음
precondition들을 일괄적으로 먼저 확인한 뒤 비즈니스 로직을 실행하는게 좋을 것 같음

2021-03-11 07:24 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +            exam.setFinished(true);
precondition이랑 비즈니스 로직을 구분하기가 어려움
precondition들을 일괄적으로 먼저 확인한 뒤 비즈니스 로직을 실행하는게 좋을 것 같음

2021-03-12 06:11 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +        if (exam.isFinished()) {throw ResponseStatusExceptions.examAlreadyFinished();}
터미널로 커밋하면 한글 깨짐

2021-03-12 06:13 UTC, tellang commented on src/test/java/kr/pullgo/pullgoserver/ExamIntegrationTest.java
> +        void cancelExam_ExamAlreadyCanceled_BadRequestStatus() throws Exception {
Canceled은 맞는 문법임

2021-03-12 06:30 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/ExamService.java
> +        if (exam.isFinished()) {throw ResponseStatusExceptions.examAlreadyFinished();}
저새끼 왜 저기가있냐

2021-03-12 07:00 UTC, woodyn1002 approved these changes

2021-03-12 07:00 UTC, merged