Add omitted attender state exception
FirstianB101/pullgo-server pull request #67
Opened 2021-03-12 15:42 UTC by tellang

close #62  close #65

2021-03-15 02:59 UTC, woodyn1002 requested changes

2021-03-15 02:59 UTC, woodyn1002 commented on src/test/java/kr/pullgo/pullgoserver/AttenderStateIntegrationTest.java
> +        void submitAttenderState_BadAttendingProgress_BadRequestStatus() throws Exception {
작성된 모든 테스트가 AttenderState의 submit이 아닌 생성 API를 테스트하고 있음 (#72와 마찬가지)

2021-03-15 02:59 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/AttenderStateService.java
> +            throw ResponseStatusExceptions
ResponseStatusExceptions 클래스는 여러 곳에서 throw되어야 하는 ResponseStatusException들을 생성해주는 팩토리 메소드를 담은 유틸 클래스임
한 곳에서만 생성되는 ResponseStatusException은 메소드로 만들지 말고 바로 인스턴스를 생성하는 편이 직관적이고 생산적이라고 생각함

2021-03-15 02:59 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    public boolean isOutOfTimeRange() {
1. 이 메소드는 AttenderState보다는 Exam에 존재하는 편이 어울림
2. 현재 시간을 하드코딩하는 것보단 메소드 인자로 받는게 테스트 가능성을 높일 수 있음
3. (일반적으로) 조건문의 형식은 `질문을 받는 표현`이 왼쪽, `비교 대상`이 오른쪽에 놓여야 가장 읽기 쉬움 (`{시작 시간}.isAfter({현재 시간})`보다 `{현재 시간}.isAfter({시작 시간})`이 직관적임)

2021-03-15 02:59 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +        LocalDateTime deadLine = examStartTime.plus(exam.getTimeLimit());
현재 시간을 하드코딩하는 것보단 메소드 인자로 받는게 테스트 가능성을 높일 수 있음

2021-03-15 02:59 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    public void setExamStartTimeToPresentTime() {
현재 시간을 하드코딩하는 것보단 메소드 인자로 받는게 테스트 가능성을 높일 수 있으므로, 새로운 메소드를 정의하기 보다는 Setter를 재정의하는 편이 좋을듯

2021-03-15 02:59 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    private LocalDateTime examStartTime = null;
AttenderState 생성 시마다 (AttenderStateService에서) examStartTime에 값을 설정하는 메소드가 호출되어야 함
지금은 항상 null이고 새 값이 절대 할당되지 않음

2021-03-15 10:37 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    public boolean isOutOfTimeRange() {
ㅇㅋ

2021-03-15 10:38 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +        LocalDateTime deadLine = examStartTime.plus(exam.getTimeLimit());
ㅇㅋ

2021-03-15 10:38 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    public void setExamStartTimeToPresentTime() {
삭제함

2021-03-15 10:40 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    private LocalDateTime examStartTime = null;
ㅇㅋ

2021-03-15 11:14 UTC, tellang commented on src/main/java/kr/pullgo/pullgoserver/service/AttenderStateService.java
> +            throw ResponseStatusExceptions
ㅇㅋ

2021-03-15 11:47 UTC, tellang commented on src/test/java/kr/pullgo/pullgoserver/AttenderStateIntegrationTest.java
> +        void submitAttenderState_BadAttendingProgress_BadRequestStatus() throws Exception {
ㅋ

2021-03-17 04:30 UTC, woodyn1002 requested changes

2021-03-17 04:30 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/persistence/model/AttenderState.java
> +    public boolean isOutOfTimeRange(LocalDateTime now) {
이 메소드는 AttenderState보다는 Exam에 존재하는 편이 어울림

2021-03-17 04:30 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/AttenderStateService.java
> +        attenderState.setProgress(AttendingProgress.ONGOING);
progress와 examStartTime 필드는 생성 시 항상 초기화되어야 하므로 setter보다는 생성자를 통해 설정하는게 좋을듯

2021-03-17 04:30 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/util/ResponseStatusExceptions.java
> +    public static ResponseStatusException attenderStateSubmittedAlreadyFinishedExam() {
ResponseStatusExceptions 클래스는 여러 곳에서 throw되어야 하는 ResponseStatusException들을 생성해주는 팩토리 메소드를 담은 유틸 클래스임
한 곳에서만 생성되는 ResponseStatusException은 메소드로 만들지 말고 바로 인스턴스를 생성하는 편이 직관적이고 생산적이라고 생각함
아래 메소드들 모두 포함

2021-03-17 05:57 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/service/AttenderStateService.java
> +        attenderState.setProgress(AttendingProgress.ONGOING);
생성자보다는 Builder로 만드는게 낫겠다

2021-03-17 05:58 UTC, woodyn1002 commented on src/main/java/kr/pullgo/pullgoserver/util/ResponseStatusExceptions.java
> +    public static ResponseStatusException attenderStateSubmittedAlreadyFinishedExam() {
별로 중요하지 않으므로 나중에 다른 코드까지 한 번에 수정하도록 결정함

2021-03-17 08:49 UTC, woodyn1002 approved these changes

2021-03-17 08:49 UTC, merged